name       : snapd
version    : 2.39.3
homepage   : https://snapcraft.io/
release    : 55
source     :
    - https://github.com/snapcore/snapd/releases/download/2.39.3/snapd_2.39.3.vendor.tar.xz : 035c75b14ec3347b5953076ff763d2ab3306c1bd8f689806675995054faf53fe
license    : GPL-3.0-only
component  : desktop.util
summary    : The snapd and snap tools enable systems to work with .snap files
description: |
    Universal applications support - .snap files allow you to run Snap packages
    on any Linux distribution, with full sandboxing and additional security.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libapparmor)
    - pkgconfig(libseccomp)
    - pkgconfig(libudev)
    - pkgconfig(libcap)
    - golang
    - python-docutils
    - xfsprogs-devel
rundeps    :
    - apparmor
    - libselinux
    - squashfs-tools
environment: |
    export import_path=github.com/snapcore/snapd
    export go_binaries=(snap snapctl snap-seccomp snap-update-ns snap-exec snapd)
    export static_binaries=(snap-update-ns snap-exec snapctl)
    export bincommands=(snap)
    export dcommands=(snapctl snapd snap-exec snap-update-ns snap-seccomp)

setup      : |
    mkdir -p src/github.com/snapcore
    ln -s `pwd` src/github.com/snapcore/snapd

    pushd src/${import_path}
    ./mkversion.sh "$version"

    %apply_patches

    pushd cmd
    %reconfigure \
        --enable-nvidia-biarch \
        --enable-merged-usr \
        --with-snap-mount-dir=/snap
    popd
build      : |
    %make -C src/${import_path}/cmd

    for snapvar in ${go_binaries[@]}; do
        GOPATH="`pwd`" go build -o bin/$snapvar -buildmode=pie --ldflags "-extldflags '$LDFLAGS'" ${import_path}/cmd/$snapvar
    done
    for staticpath in ${static_binaries[@]} ; do
        GOPATH="`pwd`" go build -o bin/$staticpath -buildmode=pie --ldflags "-extldflags '$LDFLAGS -static'" ${import_path}/cmd/$staticpath
    done
install    : |
    %make_install -C src/${import_path}/cmd

    # Golang binaries
    for snap_bin in ${bincommands[@]} ; do
        install -m00755 bin/$snap_bin $installdir/usr/bin/.
    done
    for snap_lib in ${dcommands[@]} ; do
        install -m00755 bin/$snap_lib $installdir/%libdir%/$package/.
    done
    # snapctl is run from inside the snap
    ln -s /%libdir%/$package/snapctl $installdir/usr/bin/snapctl

    # Move into the base dir so we can install stuff
    pushd src/${import_path}
    %make_install -C data/systemd \
            LIBEXECDIR="%libdir%" \
            SYSTEMDSYSTEMUNITDIR="%libdir%/systemd/system"
            SNAP_MOUNT_DIR=/snap

    install -Ddm00755 $installdir/usr/src
    install -dm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../snapd.socket $installdir/%libdir%/systemd/system/sockets.target.wants/snapd.socket

    install -Dm00644 data/info $installdir/%libdir%/$package/info
    install -Dm00644 data/polkit/io.snapcraft.snapd.policy $installdir/usr/share/polkit-1/actions/io.snapcraft.snapd.policy
    install -Dm00644 $pkgfiles/snapd.tmpfiles $installdir/%libdir%/tmpfiles.d/snapd.conf
    install -Dm00644 $pkgfiles/70-snapd.sh $installdir/usr/share/defaults/etc/profile.d/70-snapd.sh

    # Completions
    install -Dm00644 data/completion/snap $installdir/usr/share/bash-completion/completions/snap
    install -Dm00644 data/completion/complete.sh $installdir/%libdir%/snapd/complete.sh
    install -Dm00644 data/completion/etelpmoc.sh $installdir/%libdir%/snapd/etelpmoc.sh

    # remove unneeded stuff
    rm -rf $installdir/var
    rm -rf $installdir/usr/src
    rm -rf $installdir/usr/bin/ubuntu-core-launcher
    rm -rf $installdir/%libdir%/snapd/{system-shutdown,snapd.core-fixup.sh}
    rm -rf $installdir/%libdir%/systemd/system/{snapd.system-shutdown.service,snapd.autoimport.service,snapd.snap-repair.*,snapd.core-fixup.*}
